### ISSUE TITLE
Broken link found in node.py

### ISSUE THREAD

**Issue by MeesJ** [Ahmesen/TelemetryEndpoint#2]
The `zt-e.tech` domain name is no longer under our control. This link should be changed to any official Ahmesen domain name where it will be hosted at.

https://github.com/Ahmesen/TelemetryEndpoint/blob/52b7d324119821f2254f828754e8e7a7c08f511d/node.py#L24

**Comment by HYP3RDRIVES** [comment]
Heartbeat system is currently a work in progress, still undetermined if it will be processed via websockets or normal POST request

**Comment by MeesJ** [comment]
Couldn't we remove this from the code entirely to avoid hijacking of the link?

**Comment by HYP3RDRIVES** [comment]
node.py is currently unused, but yes it will be changed to use dynamic urls instead of being hard coded in

**Comment by HYP3RDRIVES** [comment]
Actually I now think node.py should be moved to its own repo, would help better in terms of organisation.
Both would need seperate file structures, different environment varliables, etc which can be achieved by moving to a seperate repo.

**Comment by MeesJ** [comment]
Go ahead and do so, so we can close this issue.
